FROM registry.access.redhat.com/ubi8/openjdk-17:1.14 as base
WORKDIR /deployments
COPY pom.xml ./
RUN mvn -B dependency:resolve -Dclassifier=test
RUN mvn -B dependency:resolve-plugins -Dclassifier=test
COPY src ./src

FROM base as test
CMD ["mvn", "test"]
